[2025-02-13T13:40:54.441+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:40:54.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/git_repo_dag.py for tasks to queue
[2025-02-13T13:40:54.444+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:40:54.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:40:54.485+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:40:54.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/git_repo_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/git_repo_dag.py", line 3, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2025-02-13T13:40:54.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:40:54.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/git_repo_dag.py took 0.086 seconds
[2025-02-13T13:41:25.548+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:25.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/git_repo_dag.py for tasks to queue
[2025-02-13T13:41:25.551+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:41:25.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:25.580+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:41:25.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/git_repo_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/git_repo_dag.py", line 3, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2025-02-13T13:41:25.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:25.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/git_repo_dag.py took 0.081 seconds
[2025-02-13T13:41:56.468+0000] {processor.py:186} INFO - Started process (PID=1101) to work on /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:56.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/git_repo_dag.py for tasks to queue
[2025-02-13T13:41:56.471+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:41:56.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:56.499+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:41:56.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/git_repo_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/git_repo_dag.py", line 3, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2025-02-13T13:41:56.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:41:56.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/git_repo_dag.py took 0.077 seconds
[2025-02-13T13:42:27.455+0000] {processor.py:186} INFO - Started process (PID=1103) to work on /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:42:27.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/git_repo_dag.py for tasks to queue
[2025-02-13T13:42:27.458+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:42:27.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:42:27.485+0000] {logging_mixin.py:190} INFO - [2025-02-13T13:42:27.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/git_repo_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/git_repo_dag.py", line 3, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2025-02-13T13:42:27.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/git_repo_dag.py
[2025-02-13T13:42:27.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/git_repo_dag.py took 0.074 seconds
